# Generated by Django 4.2.4 on 2023-08-31 12:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Площадка для активации игры')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.FileField(blank=True, upload_to='media_activasion/', verbose_name='Картинки активации')),
                ('url', models.SlugField(max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Активатор',
                'verbose_name_plural': 'Активаторы',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('main_image', models.FileField(blank=True, upload_to='media/images/', verbose_name='Картинки')),
                ('publisher', models.CharField(max_length=200, verbose_name='Издатель')),
                ('developer', models.CharField(max_length=200, verbose_name='Разработчик')),
                ('publicated', models.DateField(default=datetime.date.today, verbose_name='Дата выхода')),
                ('localozation', models.CharField(blank=True, choices=[(None, 'Выберите вариант локализации'), ('1', 'Полностью на русском'), ('2', 'Интерфейс на русском'), ('3', 'Субтитры на русском'), ('4', 'Отсутствует')], max_length=200, verbose_name='Локализация')),
                ('age_limit', models.PositiveSmallIntegerField(default=18, verbose_name='Возрастной рейтинг')),
                ('stock', models.BooleanField(verbose_name='Есть в наличии?')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('features', models.TextField(blank=True, verbose_name='Особенности игры')),
                ('purchase', models.TextField(blank=True, verbose_name='Что я приобретаю?')),
                ('requirements', models.TextField(verbose_name='Системные требования')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('url', models.SlugField(blank=True, max_length=200, null=True)),
                ('activasion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api_store.activasion', verbose_name='Способ активации')),
            ],
            options={
                'verbose_name': 'Игры',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Жанр')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_store.games', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание.')),
                ('img', models.FileField(blank=True, upload_to='media/images/', verbose_name='Картинки')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_store.games', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Скриншот',
                'verbose_name_plural': 'Скриншоты',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('message', models.TextField(max_length=4500, verbose_name='Сообщение')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api_store.games', verbose_name='Игра')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api_store.reviews', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='games',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_genre', to='api_store.genre', verbose_name='Жанр'),
        ),
    ]
